[tools]

# Prebuilt CLI tools
yazi = "latest"
"github:nklmilojevic/sofka" = "latest"

# Rust CLI tools
"cargo:devicon-lookup" = "latest"
"cargo:eza" = "latest"
"cargo:tree-sitter-cli" = "latest"

# Go CLI tools
"go:github.com/MSmaili/hetki" = "main"
"go:github.com/go-task/task/v3/cmd/task" = "latest"

# Runtimes (alphabetical)
bun = "latest"
go = "latest"
java = "21"
lua = "5.4"
node = "24"
python = "3.13"
rust = "latest"
